version: '3.8'

services:
  web:
    build:
      context: ./django-app
    container_name: django-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
