version: '3.8'

services:
  web:
    build:
      context: ./finance_fusion
      dockerfile: Dockerfile
    container_name: django-web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PORT=8000
    volumes:
      - ./finance_fusion:/app
      

  db:
    image: postgres:14
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: financial
      POSTGRES_PASSWORD: financial@123
      POSTGRES_DB: financial_DB
    ports:
      - "5432:5432"

volumes:
  postgres_data:
